
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrador
 */
public class Vdepositar extends javax.swing.JFrame {

    /**
     * Creates new form Vdepositar
     */
    public Vdepositar() {
        initComponents();
        initComponents2();
    }
    
    public void initComponents2(){
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_cui = new javax.swing.JTextField();
        txt_monto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_cuentas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btt_depositar = new javax.swing.JButton();
        btt_menu = new javax.swing.JButton();
        btt_buscar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Depósito");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        txt_cui.setBackground(new java.awt.Color(255, 255, 255));
        txt_cui.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_cui.setForeground(new java.awt.Color(0, 0, 0));
        txt_cui.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cui.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_monto.setBackground(new java.awt.Color(255, 255, 255));
        txt_monto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_monto.setForeground(new java.awt.Color(0, 0, 0));
        txt_monto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_monto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setBackground(new java.awt.Color(255, 51, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cuenta:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setBackground(new java.awt.Color(255, 51, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CUI:");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cbx_cuentas.setBackground(new java.awt.Color(255, 255, 255));
        cbx_cuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cuentasActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 51, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Monto:");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btt_depositar.setBackground(new java.awt.Color(255, 204, 51));
        btt_depositar.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        btt_depositar.setText("Depositar");
        btt_depositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_depositarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_depositarMouseExited(evt);
            }
        });
        btt_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_depositarActionPerformed(evt);
            }
        });

        btt_menu.setBackground(new java.awt.Color(255, 204, 51));
        btt_menu.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        btt_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        btt_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_menuMouseExited(evt);
            }
        });
        btt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_menuActionPerformed(evt);
            }
        });

        btt_buscar.setBackground(new java.awt.Color(255, 204, 51));
        btt_buscar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btt_buscar.setText("Buscar");
        btt_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_buscarMouseExited(evt);
            }
        });
        btt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbx_cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(btt_depositar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btt_menu)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txt_cui, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_cui, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(cbx_cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btt_depositar)
                    .addComponent(btt_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_cuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cuentasActionPerformed
        //        //obtener la informacion de un comboBox
        //
        //        //toma el valor del combobox selecionado
        //        //lo combiete en string
        //        //y lo coloca en el lable indice
        //        lbl_indice.setText(String.valueOf(cbx_clientes.getSelectedIndex()));
        //
        //        //Toma el valor del combo box y lo pasa la entero valorElegido
        //        int valorElegido = cbx_clientes.getSelectedIndex();
        //        VregistrarCliente pf = new VregistrarCliente();
        //
        //        //-------------------------Buscar en la listaClientes el valor seleccionado del comboBox e imprimir el apellido
        //        System.out.println(pf.listaClientes[valorElegido].getApellido());
        //
    }//GEN-LAST:event_cbx_cuentasActionPerformed

    private void btt_depositarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_depositarMouseEntered
        // TODO add your handling code here:
        btt_depositar.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_depositarMouseEntered

    private void btt_depositarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_depositarMouseExited
        // TODO add your handling code here:
        btt_depositar.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_depositarMouseExited

    private void btt_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_depositarActionPerformed

//        VregistrarCliente lista = new VregistrarCliente();
//        Cliente[] verCuentasA = lista.listaClientes;
//
//        if (txt_cui.getText().equals("") || txt_monto.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No dejar campos vacios", "Información", JOptionPane.WARNING_MESSAGE);
//        } else {
//
//
//            int valorElegido = cbx_cuentas.getSelectedIndex();
//            //double monto = verCuentasA[valorElegido].getCuentasAsociadas()[valorElegido].getSaldo();
//
//            //Para hacer las cuentas
//            Cuenta nuevaCuenta = new Cuenta(id, cui, saldo);
//
//            try {
//                boolean bandera = false;
//                //AQUI SE AGREGAN LAS CUENTAS
//                for (int i = 0; i < lista.listaClientes[valorElegido].getCuentasAsociadas().length; i++) {
//                    if (lista.listaClientes[valorElegido].getCuentasAsociadas()[i] == null) {
//                        lista.listaClientes[valorElegido].getCuentasAsociadas()[i] = nuevaCuenta;
//                        JOptionPane.showMessageDialog(null, "Cuenta creada exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
//                        bandera = true;
//                        break;
//                    }
//                }
//                if (bandera == false) {
//                    JOptionPane.showMessageDialog(null, "No es posible crear más cuentas para este cliente", "Limite de usuarios", JOptionPane.ERROR_MESSAGE);
//                }
//                for (int i = 0; i < lista.listaClientes.length; i++) {
//                    lista.listaClientes[valorElegido].getCuentasAsociadas()[i].imprimirCuenta();
//                }
//
//            } catch (NullPointerException ex) {
//            }
        
        

    }//GEN-LAST:event_btt_depositarActionPerformed

    private void btt_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_menuMouseEntered
        // TODO add your handling code here:
        btt_menu.setBackground(new java.awt.Color(255,153,51));

    }//GEN-LAST:event_btt_menuMouseEntered

    private void btt_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_menuMouseExited
        // TODO add your handling code here:
        btt_menu.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_menuMouseExited

    private void btt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_menuActionPerformed
        // TODO add your handling code here:
        VentanaMenu regresar = new VentanaMenu();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btt_menuActionPerformed

    private void btt_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_buscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_buscarMouseEntered

    private void btt_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_buscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_buscarMouseExited

    private void btt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_buscarActionPerformed

        //MOSTRNADO LOS DATOS DE LA CUENTA EN UN ComboBox
        VregistrarCliente lista = new VregistrarCliente();
        Cliente[] verCuentasA = lista.listaClientes;

        if (txt_cui.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un CUI", "Información", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int i = 0; i < verCuentasA.length; i++) {
                if (verCuentasA[i] != null) {
                    //recorriendo para saber si que el cui ingresado sea igual 
                    if (verCuentasA[i].getCui() == Integer.parseInt(txt_cui.getText())) {

                        cbx_cuentas.removeAllItems();
                        for (int j = 0; j < verCuentasA[i].getCuentasAsociadas().length; j++) {
                            if (verCuentasA[i].getCuentasAsociadas()[j] != null) {
                                cbx_cuentas.addItem(String.valueOf(verCuentasA[i].getCuentasAsociadas()[j].getId()) + " " + verCuentasA[i].getNombre() + " " + verCuentasA[i].getApellido());
                            }
                        }                     
                    }
                }
            }
            
        }
        
    }//GEN-LAST:event_btt_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vdepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vdepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vdepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vdepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vdepositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_buscar;
    private javax.swing.JButton btt_depositar;
    private javax.swing.JButton btt_menu;
    private javax.swing.JComboBox<String> cbx_cuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_cui;
    private javax.swing.JTextField txt_monto;
    // End of variables declaration//GEN-END:variables
}
