/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrador
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
        initComponents2();
    }
    
    public void initComponents2(){
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btt_CrearCuenta = new javax.swing.JButton();
        btt_Clientes = new javax.swing.JButton();
        btt_InfoClientes = new javax.swing.JButton();
        btt_Deposito = new javax.swing.JButton();
        btt_Transferencia = new javax.swing.JButton();
        btt_Servicios = new javax.swing.JButton();
        btt_Historial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btt_CrearCuenta.setBackground(new java.awt.Color(255, 204, 51));
        btt_CrearCuenta.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_CrearCuenta.setText("Crear Cuenta");
        btt_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_CrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_CrearCuentaMouseExited(evt);
            }
        });
        btt_CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_CrearCuentaActionPerformed(evt);
            }
        });

        btt_Clientes.setBackground(new java.awt.Color(255, 204, 51));
        btt_Clientes.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_Clientes.setText("Regristrar Clientes");
        btt_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_ClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_ClientesMouseExited(evt);
            }
        });
        btt_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_ClientesActionPerformed(evt);
            }
        });

        btt_InfoClientes.setBackground(new java.awt.Color(255, 204, 51));
        btt_InfoClientes.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_InfoClientes.setText("Información");
        btt_InfoClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_InfoClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_InfoClientesMouseExited(evt);
            }
        });
        btt_InfoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_InfoClientesActionPerformed(evt);
            }
        });

        btt_Deposito.setBackground(new java.awt.Color(255, 204, 51));
        btt_Deposito.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_Deposito.setText("Depósito");
        btt_Deposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_DepositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_DepositoMouseExited(evt);
            }
        });
        btt_Deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_DepositoActionPerformed(evt);
            }
        });

        btt_Transferencia.setBackground(new java.awt.Color(255, 204, 51));
        btt_Transferencia.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_Transferencia.setText("Transferencia");
        btt_Transferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_TransferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_TransferenciaMouseExited(evt);
            }
        });
        btt_Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_TransferenciaActionPerformed(evt);
            }
        });

        btt_Servicios.setBackground(new java.awt.Color(255, 204, 51));
        btt_Servicios.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_Servicios.setText("Servicios");
        btt_Servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_ServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_ServiciosMouseExited(evt);
            }
        });
        btt_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_ServiciosActionPerformed(evt);
            }
        });

        btt_Historial.setBackground(new java.awt.Color(255, 204, 51));
        btt_Historial.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        btt_Historial.setText("Historial");
        btt_Historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btt_HistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btt_HistorialMouseExited(evt);
            }
        });
        btt_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_HistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btt_Historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btt_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btt_Deposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btt_InfoClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btt_Transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btt_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btt_CrearCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btt_Transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt_InfoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_Deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btt_Historial)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Operaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_CrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_CrearCuentaMouseEntered
        // TODO add your handling code here:
        btt_CrearCuenta.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_CrearCuentaMouseEntered

    private void btt_CrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_CrearCuentaMouseExited
        // TODO add your handling code here:
        btt_CrearCuenta.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_CrearCuentaMouseExited

    private void btt_CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_CrearCuentaActionPerformed
        // TODO add your handling code here:
        
        VcrearCuentas crearCuenta = new VcrearCuentas();
        crearCuenta.setVisible(true);
        
        this.setVisible(false);
        new VentanaMenu().setVisible(false);
        
        
        
        /*
        VentanaLogin ventana2 = new VentanaLogin();
        ventana2.setVisible(true);
        */
    }//GEN-LAST:event_btt_CrearCuentaActionPerformed

    private void btt_ClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_ClientesMouseEntered
        // TODO add your handling code here:
        btt_Clientes.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_ClientesMouseEntered

    private void btt_ClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_ClientesMouseExited
        // TODO add your handling code here:
        btt_Clientes.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_ClientesMouseExited

    private void btt_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_ClientesActionPerformed
        // TODO add your handling code here:
        VregistrarCliente crearCliente = new VregistrarCliente();
        crearCliente.setVisible(true);
        
        this.setVisible(false);
        new VentanaMenu().setVisible(false);
        
    }//GEN-LAST:event_btt_ClientesActionPerformed

    private void btt_InfoClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_InfoClientesMouseEntered
        // TODO add your handling code here:
        btt_InfoClientes.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_InfoClientesMouseEntered

    private void btt_InfoClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_InfoClientesMouseExited
        // TODO add your handling code here:
        btt_InfoClientes.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_InfoClientesMouseExited

    private void btt_InfoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_InfoClientesActionPerformed
        // TODO add your handling code here:
        VinfoClientes llamarVentana = new VinfoClientes();
        llamarVentana.setVisible(true);
        
        this.setVisible(false);
        //new VentanaMenu().setVisible(false);
    }//GEN-LAST:event_btt_InfoClientesActionPerformed

    private void btt_DepositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_DepositoMouseEntered
        // TODO add your handling code here:
        btt_Deposito.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_DepositoMouseEntered

    private void btt_DepositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_DepositoMouseExited
        // TODO add your handling code here:
        btt_Deposito.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_DepositoMouseExited

    private void btt_DepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_DepositoActionPerformed
        // TODO add your handling code here:
        Vdepositar llamarVentana = new Vdepositar();
        llamarVentana.setVisible(true);
        
        this.setVisible(false);
       
    }//GEN-LAST:event_btt_DepositoActionPerformed

    private void btt_TransferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_TransferenciaMouseEntered
        // TODO add your handling code here:
        btt_Transferencia.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_TransferenciaMouseEntered

    private void btt_TransferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_TransferenciaMouseExited
        // TODO add your handling code here:
        btt_Transferencia.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_TransferenciaMouseExited

    private void btt_TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_TransferenciaActionPerformed
        // TODO add your handling code here:
        Vtransferencia llamarVentana = new Vtransferencia();
        llamarVentana.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btt_TransferenciaActionPerformed

    private void btt_ServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_ServiciosMouseEntered
        // TODO add your handling code here:
        btt_Servicios.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_ServiciosMouseEntered

    private void btt_ServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_ServiciosMouseExited
        // TODO add your handling code here:
        btt_Servicios.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_ServiciosMouseExited

    private void btt_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_ServiciosActionPerformed
        // TODO add your handling code here:
        Vservicio llamarVentana = new Vservicio();
        llamarVentana.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btt_ServiciosActionPerformed

    private void btt_HistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_HistorialMouseEntered
        // TODO add your handling code here:
        btt_Historial.setBackground(new java.awt.Color(255,153,51));
    }//GEN-LAST:event_btt_HistorialMouseEntered

    private void btt_HistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btt_HistorialMouseExited
        // TODO add your handling code here:
        btt_Historial.setBackground(new java.awt.Color(255,204,51));
    }//GEN-LAST:event_btt_HistorialMouseExited

    private void btt_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_HistorialActionPerformed
        // TODO add your handling code here:
        Vhistorial llamarVentana = new Vhistorial();
        llamarVentana.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btt_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_Clientes;
    private javax.swing.JButton btt_CrearCuenta;
    private javax.swing.JButton btt_Deposito;
    private javax.swing.JButton btt_Historial;
    private javax.swing.JButton btt_InfoClientes;
    private javax.swing.JButton btt_Servicios;
    private javax.swing.JButton btt_Transferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
